// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalTeamManager.Infrastructure.Persistence;

#nullable disable

namespace NationalTeamManager.Infrastructure.Migrations
{
    [DbContext(typeof(NationalTeamManagerDbContext))]
    [Migration("20260910143426_AddTeamsAndCompetitionStructure")]
    partial class AddTeamsAndCompetitionStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId", "DataSource")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL AND [DataSource] IS NOT NULL");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.CompetitionEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Year")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("ExternalId", "DataSource")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL AND [DataSource] IS NOT NULL");

                    b.ToTable("CompetitionEditions");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.CompetitionStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionEditionId")
                        .HasColumnType("int");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionEditionId");

                    b.HasIndex("ExternalId", "DataSource")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL AND [DataSource] IS NOT NULL");

                    b.ToTable("CompetitionStages");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionEditionId")
                        .HasColumnType("int");

                    b.Property<int?>("CompetitionStageId")
                        .HasColumnType("int");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionEditionId");

                    b.HasIndex("CompetitionStageId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("ExternalId", "DataSource")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL AND [DataSource] IS NOT NULL");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("PreferredFoot")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("ExternalId", "DataSource")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL AND [DataSource] IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.PlayerMarketValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "RecordedAt")
                        .IsUnique();

                    b.ToTable("PlayerMarketValues");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsNationalTeam")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId", "DataSource")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL AND [DataSource] IS NOT NULL");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.CompetitionEdition", b =>
                {
                    b.HasOne("NationalTeamManager.Domain.Entities.Competition", "Competition")
                        .WithMany("Editions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.CompetitionStage", b =>
                {
                    b.HasOne("NationalTeamManager.Domain.Entities.CompetitionEdition", "CompetitionEdition")
                        .WithMany("Stages")
                        .HasForeignKey("CompetitionEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionEdition");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Match", b =>
                {
                    b.HasOne("NationalTeamManager.Domain.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NationalTeamManager.Domain.Entities.CompetitionEdition", "CompetitionEdition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionEditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NationalTeamManager.Domain.Entities.CompetitionStage", "CompetitionStage")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NationalTeamManager.Domain.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("CompetitionEdition");

                    b.Navigation("CompetitionStage");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Player", b =>
                {
                    b.HasOne("NationalTeamManager.Domain.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.PlayerMarketValue", b =>
                {
                    b.HasOne("NationalTeamManager.Domain.Entities.Player", "Player")
                        .WithMany("MarketValues")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Competition", b =>
                {
                    b.Navigation("Editions");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.CompetitionEdition", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.CompetitionStage", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Player", b =>
                {
                    b.Navigation("MarketValues");
                });

            modelBuilder.Entity("NationalTeamManager.Domain.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
